### ISSUE TITLE
Reproducing Paper's Results

### ISSUE THREAD

**Issue by alirezazareian** [abdulfatir/prototypical-networks-tensorflow#2]
Dear Abdul,

Your implementation of the mini-imagenet experiment yields an accuracy of 0.61 while it is reported to be 0.68 in the paper. What do you think the issue is? Have you tried to close the gap?

Thanks;
Ali

**Comment by abdulfatir** [comment]
Hi Ali,

I didn't spend much time trying to reproduce results. The results in this repo are from a random run. Also, note that the mini-Imagenet used by me is different from the one used in the paper.
