### ISSUE TITLE
Reproducibility of the script for mini-imagenet ?

### ISSUE THREAD

**Issue by debasmitdas** [abdulfatir/prototypical-networks-tensorflow#3]
Do you know how to add random seeds so that running the script again and again produces the same result ?
Adding 
tf.set_random_seed(1)
np.random.seed(1) 
at the beginning does not work

**Comment by abdulfatir** [comment]
It will be reproducible if you are trying on a CPU (which probably isn't the case). On GPU it will be reproducible only if the underlying CUDA kernel is reproducible which may not be the case for some TF ops.
